title: OS Guidebook for Neuroscience
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://marbarrantescepas.github.io/open-neuroscience-anw

aux_links:
  Template Repository: https://marbarrantescepas.github.io/open-neuroscience-anw
